language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: false

script:
  - ./vendor/bin/phpunit -v

before_script:
  - composer self-update
  - composer install

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
